name: "size"
on:
  pull_request:
    branches:
      - master
permissions:
  pull-requests: write
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: EskiMojo14/size-limit-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build-only
          size_margin: non-zero
